GET localhost:8080/customer/findAll

###

GET localhost:8080/customer/findCustomer/1

###

POST localhost:8080/customer/addCustomer
Content-Type: application/json

{
  "id": 2,
  "name": "Mario Mayr",
  "dateOfBirth": "1999-05-11"
}

###

PUT localhost:8080/customer/2
Content-Type: application/json

{
  "id": 2,
  "name": "Peter Gruber",
  "dateOfBirth": "1999-05-11"
}

###

DELETE localhost:8080/customer/deleteCustomer/2

###

