@startuml
class Car{
-id: int
-name: String
-preis: double
}

class Customer{
-id: int
-name: String
-dateOfBirth: LocalDate
}

class Rental{
-car: Auto
-customer: Kunde
-startDatum: LocalDate
-endDatum: LocalDate
-discount: double
}

Car "1" <- "*" Rental : is rented
Rental "*" -> "1" Customer : rents


@enduml
